### ISSUE TITLE
[Member] BUG-48

### ISSUE THREAD

**Issue by SWARVY** [KGU-C-Lab/clab.page#166]
### 버그 설명

멤버 프로젝트에 발생한 BUG 48을 수정합니다

### Tasks

- [x] 모아보기 섹션에 존재하는 제목 아래 컨텐츠 영역에서 변환되지 않은 html 태그 변환

**Comment by gwansikk** [comment]
@SWARVY 해당 이슈는 `toDecodeHTMLEntities` 함수를 사용하면 쉽게 해결할 수 있어요~

**Comment by SWARVY** [comment]
아고 이미 있었네요 해당내용 적용하여 해당 에러 조치하겠습니다~
